# Generated by Django 5.2.6 on 2025-09-14 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Filter name for your reference', max_length=100)),
                ('exchange', models.CharField(blank=True, choices=[('', 'All Exchanges'), ('US', 'US Markets'), ('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('AMEX', 'American Stock Exchange')], default='', max_length=20)),
                ('sector', models.CharField(blank=True, choices=[('', 'All Sectors'), ('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Financial Services', 'Financial Services'), ('Consumer Cyclical', 'Consumer Cyclical'), ('Communication Services', 'Communication Services'), ('Industrials', 'Industrials'), ('Consumer Defensive', 'Consumer Defensive'), ('Energy', 'Energy'), ('Real Estate', 'Real Estate'), ('Materials', 'Materials'), ('Utilities', 'Utilities')], default='', max_length=50)),
                ('min_market_cap', models.BigIntegerField(blank=True, help_text='Minimum market cap in millions USD', null=True)),
                ('max_market_cap', models.BigIntegerField(blank=True, help_text='Maximum market cap in millions USD', null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum stock price', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stock price', max_digits=10, null=True)),
                ('min_volume', models.BigIntegerField(blank=True, help_text='Minimum daily volume', null=True)),
                ('min_pe_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum P/E ratio', max_digits=8, null=True)),
                ('max_pe_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum P/E ratio', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=20)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
