# Generated by Django 5.2.6 on 2025-09-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfilter',
            name='below_moving_average_only',
            field=models.BooleanField(default=True, help_text='Show only stocks below their moving average (value buy indicator)'),
        ),
        migrations.AddField(
            model_name='companyfilter',
            name='enable_moving_average_filter',
            field=models.BooleanField(default=False, help_text='Enable moving average filter'),
        ),
        migrations.AddField(
            model_name='companyfilter',
            name='moving_average_period',
            field=models.IntegerField(choices=[(20, '20-day MA'), (50, '50-day MA'), (100, '100-day MA'), (200, '200-day MA')], default=50, help_text='Moving average period in days'),
        ),
    ]
