# Generated by Django 5.2.6 on 2025-09-15 02:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_companyfilter_below_moving_average_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP500Company',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company is currently in S&P 500')),
                ('added_to_sp500', models.DateField(blank=True, help_text='Date when added to S&P 500', null=True)),
                ('removed_from_sp500', models.DateField(blank=True, help_text='Date when removed from S&P 500', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'S&P 500 Company',
                'verbose_name_plural': 'S&P 500 Companies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market cap in USD', null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_to_book', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('ma_20', models.DecimalField(blank=True, decimal_places=4, help_text='20-day moving average', max_digits=12, null=True)),
                ('ma_50', models.DecimalField(blank=True, decimal_places=4, help_text='50-day moving average', max_digits=12, null=True)),
                ('ma_100', models.DecimalField(blank=True, decimal_places=4, help_text='100-day moving average', max_digits=12, null=True)),
                ('ma_200', models.DecimalField(blank=True, decimal_places=4, help_text='200-day moving average', max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='insights.sp500company')),
            ],
            options={
                'ordering': ['-date', 'company__symbol'],
                'indexes': [models.Index(fields=['date'], name='insights_co_date_98edad_idx'), models.Index(fields=['last_updated'], name='insights_co_last_up_989b16_idx'), models.Index(fields=['company', 'date'], name='insights_co_company_ff1d43_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
