# Generated by Django 5.2.6 on 2025-09-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_sp500company_companymetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymetrics',
            name='daily_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Daily price change', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='daily_change_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Daily change percentage', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='monthly_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Monthly price change', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='monthly_change_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Monthly change percentage', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='sector',
            field=models.CharField(blank=True, help_text='Company sector', max_length=100),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='yearly_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Yearly price change', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companymetrics',
            name='yearly_change_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Yearly change percentage', max_digits=8, null=True),
        ),
    ]
