from django.core.management.base import BaseCommand
from insights.models import SP500Company


class Command(BaseCommand):
    help = 'Populate the database with S&P 500 companies'

    def handle(self, *args, **options):
        # Complete S&P 500 companies list
        sp500_companies = [
            ('MMM', '3M'),
            ('AOS', 'A. O. Smith'),
            ('ABT', 'Abbott Laboratories'),
            ('ABBV', 'AbbVie'),
            ('ACN', 'Accenture'),
            ('ADBE', 'Adobe Inc.'),
            ('AMD', 'Advanced Micro Devices'),
            ('AES', 'AES Corporation'),
            ('AFL', 'Aflac'),
            ('A', 'Agilent Technologies'),
            ('APD', 'Air Products and Chemicals'),
            ('ABNB', 'Airbnb'),
            ('AKAM', 'Akamai Technologies'),
            ('ALB', 'Albemarle Corporation'),
            ('ARE', 'Alexandria Real Estate Equities'),
            ('ALGN', 'Align Technology'),
            ('ALLE', 'Allegion'),
            ('LNT', 'Alliant Energy'),
            ('ALL', 'Allstate'),
            ('GOOGL', 'Alphabet Inc. (Class A)'),
            ('GOOG', 'Alphabet Inc. (Class C)'),
            ('MO', 'Altria Group'),
            ('AMZN', 'Amazon'),
            ('AMCR', 'Amcor'),
            ('AMGN', 'Amgen'),
            ('AMP', 'Ameriprise Financial'),
            ('AMT', 'American Tower'),
            ('AWK', 'American Water Works'),
            ('AXP', 'American Express'),
            ('AIG', 'American International Group'),
            ('AME', 'AMETEK'),
            ('AMTM', 'Amtm'),
            ('NLY', 'Annaly Capital Management'),
            ('ANSS', 'Ansys'),
            ('ANTM', 'Anthem'),
            ('AON', 'Aon'),
            ('APA', 'APA Corporation'),
            ('AAPL', 'Apple'),
            ('AMAT', 'Applied Materials'),
            ('APTV', 'Aptiv'),
            ('ANET', 'Arista Networks'),
            ('AJG', 'Arthur J. Gallagher & Co.'),
            ('AIZ', 'Assurant'),
            ('T', 'AT&T'),
            ('ATO', 'Atmos Energy'),
            ('ADSK', 'Autodesk'),
            ('ADP', 'Automatic Data Processing'),
            ('AZO', 'AutoZone'),
            ('AVB', 'AvalonBay Communities'),
            ('AVY', 'Avery Dennison'),
            ('AXON', 'Axon Enterprise'),
            ('BKR', 'Baker Hughes'),
            ('BALL', 'Ball Corporation'),
            ('BAC', 'Bank of America'),
            ('BBWI', 'Bath & Body Works'),
            ('BAX', 'Baxter International'),
            ('BDX', 'Becton Dickinson'),
            ('WRB', 'Berkshire Hathaway'),
            ('BRK.B', 'Berkshire Hathaway'),
            ('BBY', 'Best Buy'),
            ('BIO', 'Bio-Rad Laboratories'),
            ('TECH', 'Bio-Techne'),
            ('BIIB', 'Biogen'),
            ('BLK', 'BlackRock'),
            ('BK', 'Bank of New York Mellon'),
            ('BA', 'Boeing'),
            ('BKNG', 'Booking Holdings'),
            ('BWA', 'BorgWarner'),
            ('BSX', 'Boston Scientific'),
            ('BMY', 'Bristol Myers Squibb'),
            ('AVGO', 'Broadcom'),
            ('BR', 'Broadridge Financial Solutions'),
            ('BRO', 'Brown & Brown'),
            ('CHRW', 'C.H. Robinson'),
            ('CDNS', 'Cadence Design Systems'),
            ('CZR', 'Caesars Entertainment'),
            ('CPT', 'Camden Property Trust'),
            ('CPB', 'Campbell Soup Company'),
            ('COF', 'Capital One'),
            ('CAH', 'Cardinal Health'),
            ('KMX', 'CarMax'),
            ('CCL', 'Carnival Corporation'),
            ('CARR', 'Carrier Global'),
            ('CTLT', 'Catalent'),
            ('CAT', 'Caterpillar'),
            ('CBOE', 'Cboe Global Markets'),
            ('CBRE', 'CBRE Group'),
            ('CDW', 'CDW Corporation'),
            ('CE', 'Celanese'),
            ('COR', 'Cencora'),
            ('CNC', 'Centene Corporation'),
            ('CNP', 'CenterPoint Energy'),
            ('CDAY', 'Ceridian HCM Holding'),
            ('CF', 'CF Industries'),
            ('CRL', 'Charles River Laboratories'),
            ('SCHW', 'Charles Schwab Corporation'),
            ('CHTR', 'Charter Communications'),
            ('CVX', 'Chevron Corporation'),
            ('CMG', 'Chipotle Mexican Grill'),
            ('CB', 'Chubb Limited'),
            ('CHD', 'Church & Dwight'),
            ('CI', 'Cigna'),
            ('CINF', 'Cincinnati Financial'),
            ('CTAS', 'Cintas Corporation'),
            ('CSCO', 'Cisco Systems'),
            ('C', 'Citigroup'),
            ('CFG', 'Citizens Financial Group'),
            ('CLX', 'Clorox Company'),
            ('CME', 'CME Group'),
            ('CMS', 'CMS Energy'),
            ('KO', 'Coca-Cola Company'),
            ('CTSH', 'Cognizant Technology Solutions'),
            ('CL', 'Colgate-Palmolive'),
            ('CMCSA', 'Comcast'),
            ('CMA', 'Comerica'),
            ('CAG', 'Conagra Brands'),
            ('COP', 'ConocoPhillips'),
            ('ED', 'Consolidated Edison'),
            ('STZ', 'Constellation Brands'),
            ('CEG', 'Constellation Energy'),
            ('COO', 'Cooper Companies'),
            ('CPRT', 'Copart'),
            ('GLW', 'Corning Inc.'),
            ('CPAY', 'Corpay'),
            ('CTVA', 'Corteva'),
            ('CSGP', 'CoStar Group'),
            ('COST', 'Costco'),
            ('CTRA', 'Coterra Energy'),
            ('CCI', 'Crown Castle'),
            ('CSX', 'CSX Corporation'),
            ('CMI', 'Cummins'),
            ('CVS', 'CVS Health'),
            ('DHI', 'D.R. Horton'),
            ('DHR', 'Danaher Corporation'),
            ('DRI', 'Darden Restaurants'),
            ('DVA', 'DaVita'),
            ('DE', 'Deere & Company'),
            ('DAL', 'Delta Air Lines'),
            ('XRAY', 'Dentsply Sirona'),
            ('DVN', 'Devon Energy'),
            ('DXCM', 'DexCom'),
            ('FANG', 'Diamondback Energy'),
            ('DFS', 'Discover Financial Services'),
            ('DIS', 'Walt Disney Company'),
            ('DG', 'Dollar General'),
            ('DLTR', 'Dollar Tree'),
            ('D', 'Dominion Energy'),
            ('DPZ', 'Domino\'s Pizza'),
            ('DOV', 'Dover Corporation'),
            ('DOW', 'Dow Inc.'),
            ('DTE', 'DTE Energy'),
            ('DUK', 'Duke Energy'),
            ('DD', 'DuPont'),
            ('DXC', 'DXC Technology'),
            ('EMN', 'Eastman Chemical Company'),
            ('ETN', 'Eaton Corporation'),
            ('EBAY', 'eBay'),
            ('ECL', 'Ecolab'),
            ('EIX', 'Edison International'),
            ('EW', 'Edwards Lifesciences'),
            ('EA', 'Electronic Arts'),
            ('ELV', 'Elevance Health'),
            ('LLY', 'Eli Lilly and Company'),
            ('EMR', 'Emerson Electric Company'),
            ('ENPH', 'Enphase Energy'),
            ('EQT', 'EQT Corporation'),
            ('EFX', 'Equifax'),
            ('EQIX', 'Equinix'),
            ('EQR', 'Equity Residential'),
            ('ESS', 'Essex Property Trust'),
            ('EL', 'Estée Lauder Companies'),
            ('ETSY', 'Etsy'),
            ('RE', 'Everest Group'),
            ('EVRG', 'Evergy'),
            ('ES', 'Eversource Energy'),
            ('EXC', 'Exelon Corporation'),
            ('EXPE', 'Expedia Group'),
            ('EXPD', 'Expeditors'),
            ('EXR', 'Extended Stay America'),
            ('XOM', 'Exxon Mobil'),
            ('FFIV', 'F5, Inc.'),
            ('FB', 'Meta Platforms'),
            ('FAST', 'Fastenal'),
            ('FRT', 'Federal Realty Investment Trust'),
            ('FDX', 'FedEx Corporation'),
            ('FITB', 'Fifth Third Bancorp'),
            ('FSLR', 'First Solar'),
            ('FE', 'FirstEnergy'),
            ('FIS', 'Fidelity National Information Services'),
            ('FISV', 'Fiserv'),
            ('FLT', 'FleetCor Technologies'),
            ('FMC', 'FMC Corporation'),
            ('F', 'Ford Motor Company'),
            ('FTNT', 'Fortinet'),
            ('FTV', 'Fortive'),
            ('FOXA', 'Fox Corporation'),
            ('FOX', 'Fox Corporation'),
            ('BEN', 'Franklin Resources'),
            ('FCX', 'Freeport-McMoRan'),
            ('GRMN', 'Garmin'),
            ('IT', 'Gartner'),
            ('GNRC', 'Generac Holdings'),
            ('GD', 'General Dynamics'),
            ('GE', 'General Electric'),
            ('GIS', 'General Mills'),
            ('GM', 'General Motors'),
            ('GPC', 'Genuine Parts Company'),
            ('GILD', 'Gilead Sciences'),
            ('GPN', 'Global Payments'),
            ('GL', 'Globe Life'),
            ('GS', 'Goldman Sachs'),
            ('HAL', 'Halliburton'),
            ('HIG', 'Hartford Financial Services Group'),
            ('HAS', 'Hasbro'),
            ('HCA', 'HCA Healthcare'),
            ('PEAK', 'Healthpeak Properties'),
            ('HSIC', 'Henry Schein'),
            ('HSY', 'Hershey Company'),
            ('HES', 'Hess Corporation'),
            ('HPE', 'Hewlett Packard Enterprise'),
            ('HLT', 'Hilton Worldwide'),
            ('HOLX', 'Hologic'),
            ('HD', 'Home Depot'),
            ('HON', 'Honeywell'),
            ('HRL', 'Hormel Foods'),
            ('HST', 'Host Hotels & Resorts'),
            ('HWM', 'Howmet Aerospace'),
            ('HPQ', 'HP Inc.'),
            ('HUM', 'Humana'),
            ('HBAN', 'Huntington Bancshares'),
            ('HII', 'Huntington Ingalls Industries'),
            ('IBM', 'International Business Machines'),
            ('IEX', 'IDEX Corporation'),
            ('IDXX', 'IDEXX Laboratories'),
            ('INFO', 'IHS Markit'),
            ('IFF', 'International Flavors & Fragrances'),
            ('ILMN', 'Illumina'),
            ('INCY', 'Incyte'),
            ('IR', 'Ingersoll Rand'),
            ('INTC', 'Intel Corporation'),
            ('ICE', 'Intercontinental Exchange'),
            ('IRM', 'Iron Mountain'),
            ('INTU', 'Intuit'),
            ('ISRG', 'Intuitive Surgical'),
            ('IVZ', 'Invesco'),
            ('INVH', 'Invitation Homes'),
            ('IQV', 'IQVIA'),
            ('IFF', 'International Flavors & Fragrances'),
            ('JBHT', 'J.B. Hunt Transport Services'),
            ('JKHY', 'Jack Henry & Associates'),
            ('J', 'Jacobs Solutions'),
            ('JNJ', 'Johnson & Johnson'),
            ('JCI', 'Johnson Controls'),
            ('JPM', 'JPMorgan Chase'),
            ('JNPR', 'Juniper Networks'),
            ('K', 'Kellogg Company'),
            ('KEY', 'KeyCorp'),
            ('KEYS', 'Keysight Technologies'),
            ('KMB', 'Kimberly-Clark'),
            ('KIM', 'Kimco Realty'),
            ('KMI', 'Kinder Morgan'),
            ('KLAC', 'KLA Corporation'),
            ('KHC', 'Kraft Heinz Company'),
            ('KR', 'Kroger Company'),
            ('LHX', 'L3Harris Technologies'),
            ('LH', 'LabCorp'),
            ('LRCX', 'Lam Research'),
            ('LW', 'Lamb Weston Holdings'),
            ('LVS', 'Las Vegas Sands'),
            ('LDOS', 'Leidos'),
            ('LEN', 'Lennar Corporation'),
            ('LNC', 'Lincoln National'),
            ('LIN', 'Linde'),
            ('LYV', 'Live Nation Entertainment'),
            ('LKQ', 'LKQ Corporation'),
            ('LMT', 'Lockheed Martin'),
            ('L', 'Loews Corporation'),
            ('LOW', 'Lowe\'s Companies'),
            ('LULU', 'Lululemon Athletica'),
            ('LYB', 'LyondellBasell'),
            ('MTB', 'M&T Bank'),
            ('MRO', 'Marathon Oil'),
            ('MPC', 'Marathon Petroleum'),
            ('MKTX', 'MarketAxess'),
            ('MAR', 'Marriott International'),
            ('MMC', 'Marsh & McLennan'),
            ('MLM', 'Martin Marietta'),
            ('MAS', 'Masco Corporation'),
            ('MA', 'Mastercard'),
            ('MTCH', 'Match Group'),
            ('MKC', 'McCormick & Company'),
            ('MCD', 'McDonald\'s'),
            ('MCK', 'McKesson Corporation'),
            ('MDT', 'Medtronic'),
            ('MRK', 'Merck & Co.'),
            ('META', 'Meta Platforms'),
            ('MET', 'MetLife'),
            ('MTD', 'Mettler Toledo'),
            ('MGM', 'MGM Resorts International'),
            ('MCHP', 'Microchip Technology'),
            ('MU', 'Micron Technology'),
            ('MSFT', 'Microsoft'),
            ('MAA', 'Mid-America Apartment Communities'),
            ('MRNA', 'Moderna'),
            ('MHK', 'Mohawk Industries'),
            ('TAP', 'Molson Coors Beverage Company'),
            ('MDLZ', 'Mondelez International'),
            ('MPWR', 'Monolithic Power Systems'),
            ('MNST', 'Monster Beverage'),
            ('MCO', 'Moody\'s Corporation'),
            ('MS', 'Morgan Stanley'),
            ('MOS', 'Mosaic Company'),
            ('MSI', 'Motorola Solutions'),
            ('MSCI', 'MSCI Inc.'),
            ('NDAQ', 'Nasdaq'),
            ('NTAP', 'NetApp'),
            ('NFLX', 'Netflix'),
            ('NWL', 'Newell Brands'),
            ('NEM', 'Newmont'),
            ('NWSA', 'News Corporation'),
            ('NWS', 'News Corporation'),
            ('NEE', 'NextEra Energy'),
            ('NKE', 'Nike'),
            ('NI', 'NiSource'),
            ('NDSN', 'Nordson Corporation'),
            ('NSC', 'Norfolk Southern'),
            ('NTRS', 'Northern Trust'),
            ('NOC', 'Northrop Grumman'),
            ('NVDA', 'NVIDIA'),
            ('NVR', 'NVR'),
            ('NXPI', 'NXP Semiconductors'),
            ('ORLY', 'O\'Reilly Automotive'),
            ('OXY', 'Occidental Petroleum'),
            ('ODFL', 'Old Dominion Freight Line'),
            ('OMC', 'Omnicom Group'),
            ('ON', 'ON Semiconductor'),
            ('OKE', 'ONEOK'),
            ('ORCL', 'Oracle Corporation'),
            ('OGN', 'Organon & Co.'),
            ('OTIS', 'Otis Worldwide'),
            ('PCAR', 'PACCAR'),
            ('PKG', 'Packaging Corporation of America'),
            ('PANW', 'Palo Alto Networks'),
            ('PAYX', 'Paychex'),
            ('PAYC', 'Paycom Software'),
            ('PYPL', 'PayPal'),
            ('PNR', 'Pentair'),
            ('PEP', 'PepsiCo'),
            ('PFE', 'Pfizer'),
            ('PCG', 'PG&E Corporation'),
            ('PH', 'Parker-Hannifin'),
            ('PAYX', 'Paychex'),
            ('PAYC', 'Paycom Software'),
            ('PYPL', 'PayPal'),
            ('PNR', 'Pentair'),
            ('PEP', 'PepsiCo'),
            ('PFE', 'Pfizer'),
            ('PCG', 'PG&E Corporation'),
            ('PH', 'Parker-Hannifin'),
            ('PDCO', 'Patterson Companies'),
            ('PAYX', 'Paychex'),
            ('PAYC', 'Paycom Software'),
            ('PYPL', 'PayPal'),
            ('PNR', 'Pentair'),
            ('PEP', 'PepsiCo'),
            ('PFE', 'Pfizer'),
            ('PCG', 'PG&E Corporation'),
            ('PH', 'Parker-Hannifin'),
            ('PDCO', 'Patterson Companies'),
            ('PAYX', 'Paychex'),
            ('PAYC', 'Paycom Software'),
            ('PYPL', 'PayPal'),
            ('PNR', 'Pentair'),
            ('PEP', 'PepsiCo'),
            ('PFE', 'Pfizer'),
            ('PCG', 'PG&E Corporation'),
            ('PH', 'Parker-Hannifin'),
            ('PDCO', 'Patterson Companies'),
            ('PKI', 'PerkinElmer'),
            ('PFG', 'Principal Financial Group'),
            ('PM', 'Philip Morris International'),
            ('PSX', 'Phillips 66'),
            ('PNW', 'Pinnacle West Capital'),
            ('PXD', 'Pioneer Natural Resources'),
            ('PNC', 'PNC Financial Services'),
            ('POOL', 'Pool Corporation'),
            ('PPG', 'PPG Industries'),
            ('PPL', 'PPL Corporation'),
            ('PFG', 'Principal Financial Group'),
            ('PG', 'Procter & Gamble'),
            ('PGR', 'Progressive Corporation'),
            ('PLD', 'Prologis'),
            ('PRU', 'Prudential Financial'),
            ('PEG', 'Public Service Enterprise Group'),
            ('PSA', 'Public Storage'),
            ('PHM', 'PulteGroup'),
            ('PVH', 'PVH Corp.'),
            ('QRVO', 'Qorvo'),
            ('QCOM', 'Qualcomm'),
            ('PWR', 'Quanta Services'),
            ('DGX', 'Quest Diagnostics'),
            ('RL', 'Ralph Lauren Corporation'),
            ('RJF', 'Raymond James'),
            ('RTX', 'Raytheon Technologies'),
            ('O', 'Realty Income'),
            ('REG', 'Regency Centers'),
            ('REGN', 'Regeneron Pharmaceuticals'),
            ('RF', 'Regions Financial'),
            ('RSG', 'Republic Services'),
            ('RMD', 'ResMed'),
            ('RHI', 'Robert Half'),
            ('ROK', 'Rockwell Automation'),
            ('ROL', 'Rollins'),
            ('ROP', 'Roper Technologies'),
            ('ROST', 'Ross Stores'),
            ('RCL', 'Royal Caribbean Cruises'),
            ('SPGI', 'S&P Global'),
            ('CRM', 'Salesforce'),
            ('SBAC', 'SBA Communications'),
            ('SLB', 'SLB'),
            ('STX', 'Seagate Technology'),
            ('SEE', 'Sealed Air'),
            ('SRE', 'Sempra Energy'),
            ('NOW', 'ServiceNow'),
            ('SHW', 'Sherwin-Williams'),
            ('SPG', 'Simon Property Group'),
            ('SWKS', 'Skyworks Solutions'),
            ('SJM', 'Smucker Company'),
            ('SNA', 'Snap-on'),
            ('SEDG', 'SolarEdge Technologies'),
            ('SO', 'Southern Company'),
            ('LUV', 'Southwest Airlines'),
            ('SWK', 'Stanley Black & Decker'),
            ('SBUX', 'Starbucks'),
            ('STT', 'State Street Corporation'),
            ('STLD', 'Steel Dynamics'),
            ('STE', 'STERIS'),
            ('SYK', 'Stryker Corporation'),
            ('SYF', 'Synchrony Financial'),
            ('SNPS', 'Synopsys'),
            ('SYY', 'Sysco Corporation'),
            ('TMUS', 'T-Mobile US'),
            ('TROW', 'T. Rowe Price'),
            ('TTWO', 'Take-Two Interactive'),
            ('TPG', 'TPG'),
            ('TGT', 'Target Corporation'),
            ('TEL', 'TE Connectivity'),
            ('TDY', 'Teledyne Technologies'),
            ('TFX', 'Teleflex'),
            ('TER', 'Teradyne'),
            ('TSLA', 'Tesla'),
            ('TXN', 'Texas Instruments'),
            ('TXT', 'Textron'),
            ('TMO', 'Thermo Fisher Scientific'),
            ('TJX', 'TJX Companies'),
            ('TSCO', 'Tractor Supply Company'),
            ('TT', 'Trane Technologies'),
            ('TDG', 'TransDigm Group'),
            ('TRV', 'Travelers Companies'),
            ('TRMB', 'Trimble'),
            ('TFC', 'Truist Financial'),
            ('TYL', 'Tyler Technologies'),
            ('TSN', 'Tyson Foods'),
            ('USB', 'U.S. Bancorp'),
            ('UDR', 'UDR'),
            ('ULTA', 'Ulta Beauty'),
            ('UNP', 'Union Pacific'),
            ('UAL', 'United Airlines Holdings'),
            ('UPS', 'United Parcel Service'),
            ('URI', 'United Rentals'),
            ('UNH', 'UnitedHealth Group'),
            ('UHS', 'Universal Health Services'),
            ('VLO', 'Valero Energy'),
            ('VTR', 'Ventas'),
            ('VRSN', 'VeriSign'),
            ('VRSK', 'Verisk Analytics'),
            ('VZ', 'Verizon Communications'),
            ('VRTX', 'Vertex Pharmaceuticals'),
            ('VFC', 'VF Corporation'),
            ('VICI', 'VICI Properties'),
            ('V', 'Visa'),
            ('VMC', 'Vulcan Materials'),
            ('WAB', 'Wabtec Corporation'),
            ('WBA', 'Walgreens Boots Alliance'),
            ('WMT', 'Walmart'),
            ('WBD', 'Warner Bros. Discovery'),
            ('WM', 'Waste Management'),
            ('WAT', 'Waters Corporation'),
            ('WEC', 'WEC Energy Group'),
            ('WFC', 'Wells Fargo'),
            ('WELL', 'Welltower'),
            ('WST', 'West Pharmaceutical Services'),
            ('WDC', 'Western Digital'),
            ('WRK', 'WestRock'),
            ('WY', 'Weyerhaeuser'),
            ('WHR', 'Whirlpool Corporation'),
            ('WMB', 'Williams Companies'),
            ('WTW', 'Willis Towers Watson'),
            ('GWW', 'W.W. Grainger'),
            ('WYNN', 'Wynn Resorts'),
            ('XEL', 'Xcel Energy'),
            ('XYL', 'Xylem'),
            ('YUM', 'Yum! Brands'),
            ('ZBRA', 'Zebra Technologies'),
            ('ZBH', 'Zimmer Biomet'),
            ('ZION', 'Zions Bancorporation'),
            ('ZTS', 'Zoetis'),
        ]

        created_count = 0
        updated_count = 0

        self.stdout.write('Populating S&P 500 companies...')

        for symbol, name in sp500_companies:
            company, created = SP500Company.objects.get_or_create(
                symbol=symbol,
                defaults={
                    'name': name,
                    'is_active': True
                }
            )

            if created:
                created_count += 1
                self.stdout.write(f'Created: {symbol} - {name}')
            else:
                # Update the company name if it has changed
                if company.name != name:
                    company.name = name
                    company.save()
                    updated_count += 1
                    self.stdout.write(f'Updated: {symbol} - {name}')

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully populated S&P 500 companies. '
                f'Created: {created_count}, Updated: {updated_count}'
            )
        )